"""
PhishGuard -- backend/app.py
MODULE 2: Backend API Processing Module
Central Flask API that coordinates feature extraction and ML classification.

Process Flow:
  [01] Backend Flask server initialized and running
  [02] API endpoint exposed for URL analysis requests (/check_url)
  [03] Browser extension sends URL analysis request
  [04] API receives and validates incoming request
  [05] URL preprocessing performed to normalize input
  [06] Feature extraction module activated
  [07] Extracted features formatted for ML model input
  [08] Feature vector forwarded to the phishing detection model
  [09] Prediction result generated by model
  [10] API sends classification response back to browser extension

Install: pip install flask flask-cors
Run:     python app.py
"""

import sys
import os
import logging
import datetime

# Allow imports from sibling packages
sys.path.insert(0, os.path.dirname(__file__))

from flask import Flask, request, jsonify, abort, render_template

from flask_cors import CORS
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from flask_talisman import Talisman

from features.extractor import extract_features
from features.email_extractor import extract_email_features, email_feature_names
try:
    from features.virustotal import scan_url as vt_scan
except Exception:
    def vt_scan(url):
        return {"vt_available": False, "vt_malicious": 0, "vt_suspicious": 0,
                "vt_harmless": 0, "vt_total": 0, "vt_is_phishing": False, "vt_confidence": 0.0}
from dotenv import load_dotenv
load_dotenv()

from ml.detector import detector
from ml.email_detector import email_detector
from security import secure_endpoint, log_attack
import database

# -- [01] App setup -- Flask server initialized --------------------------------
app = Flask(__name__)

# -- Detailed Origin Enforcement via Environment (CORS) --
mode = os.environ.get("MODE", "development")
if mode == "production":
    ext_id = os.environ.get("EXTENSION_ID", "")
    netlify = os.environ.get("NETLIFY_SITE", "")
    origins = []
    if ext_id and ext_id != "your_extension_id_here":
        origins.append(f"chrome-extension://{ext_id}")
    if netlify and netlify != "your_netlify_site_here":
        origins.append(netlify)
    CORS(app, resources={r"/*": {"origins": origins}})
else:
    CORS(app)  # Dev allows more origins, but still filtered by security.py regex

# -- Security Headers --
csp = {
    'default-src': '\'self\'',
}
Talisman(app, content_security_policy=csp, force_https=(mode == "production"))

# -- Rate Limiting --
limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=["200 per day", "50 per hour"],
    storage_uri="memory://"
)

# -- IDS Attack Logger Hooks --
@app.errorhandler(429)
def ratelimit_handler(e):
    log_attack("rate_limit_violation", str(e.description))
    return jsonify(error="Rate limit exceeded. Intrusion logged."), 429

@app.errorhandler(405)
def method_not_allowed_handler(e):
    log_attack("invalid_method", "Attempted scanning/probing via invalid HTTP method")
    return jsonify(error="Method not allowed"), 405

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-7s  %(message)s",
    datefmt="%H:%M:%S"
)
logger = logging.getLogger(__name__)

# -- Request log (in-memory, last 500) ----------------------------------------
# Replaced with persistent SQLite database


# -- Root endpoint (fixes Render 404s) ----------------------------------------
@app.route("/", methods=["GET", "HEAD"])
def index():
    return jsonify({
        "status": "online",
        "service": "PhishGuard API",
        "endpoints": ["/check_url", "/check_email", "/health", "/api/version"]
    })



# -- [NEW] Forced Update Endpoint ---------------------------------------------
@app.route("/api/version", methods=["GET", "POST"])
def get_version():
    """Returns the latest required extension version and download URL."""
    netlify_url = os.environ.get("NETLIFY_SITE", "https://phishguard.netlify.app")
    if netlify_url == "your_netlify_site_here":
        netlify_url = "https://phishguard.netlify.app"
        
    return jsonify({
        "latest_version": "2.0.0",  # Change this to force an update!
        "force_update": True,
        "download_url": f"{netlify_url}"
    })


# -- [02] Main endpoint: /check_url -------------------------------------------
@app.route("/check_url", methods=["POST"])
@secure_endpoint
@limiter.limit("60 per minute")
def check_url():
    """
    Main phishing analysis endpoint.
    
    Receives:  { "url": "https://example.com" }
    Returns:   { "result": "safe" or "phishing", "confidence": 0.95 }
    """
    data = request.get_json(silent=True)
    if not data or "url" not in data:
        return jsonify({"error": "Missing 'url' field"}), 400

    url = str(data["url"]).strip()
    ts = datetime.datetime.utcnow().isoformat()

    logger.info(f"[check_url] Analyzing -> {url[:80]}")

    # [05] Preprocess / normalize URL
    if not url.startswith(("http://", "https://")):
        url = "https://" + url

    # [06] Feature extraction (instant)
    features = extract_features(url)

    # [07-08] ML prediction (instant — ~5ms)
    prediction = detector.predict(features)

    # [09] Build response immediately (no waiting for external APIs)
    result_label = "phishing" if prediction["is_phishing"] else "safe"
    confidence = round(prediction["confidence"], 4)

    response = {
        "result": result_label,
        "confidence": confidence,
    }

    # [08b] VirusTotal runs in background (non-blocking)
    # Results are cached — next scan of same URL will include VT data
    import threading
    threading.Thread(target=vt_scan, args=(url,), daemon=True).start()

    # Log result to SQLite
    database.log_request(url, result_label, confidence, prediction.get("risk_level", "unknown"), ts)

    # Console summary
    icon = "[!] PHISHING" if result_label == "phishing" else "[OK] safe   "
    logger.info(f"  {icon}  confidence={confidence*100:.0f}%  result={result_label}")

    # [10] Return to extension
    return jsonify(response), 200


# -- [MODULE 5] Email phishing endpoint (v2.0 — XGBoost + Calibrated Scoring) --
@app.route("/check_email", methods=["POST"])
@secure_endpoint
@limiter.limit("60 per minute")
def check_email():
    """
    Email phishing analysis endpoint (v2.0).
    Receives:  { "email_text": "...", "sender": "...", "subject": "..." }
    """
    data = request.get_json(silent=True)
    if not data or "email_text" not in data:
        return jsonify({"error": "Missing 'email_text' field"}), 400

    email_text = str(data["email_text"]).strip()
    sender = str(data.get("sender", "")).strip()
    subject = str(data.get("subject", "")).strip()
    ts = datetime.datetime.utcnow().isoformat()

    if not email_text:
        return jsonify({"error": "Email text cannot be empty"}), 400

    logger.info(f"[check_email] Analyzing email — sender={sender[:40]}, subject={subject[:40]}")

    # [1] Extract 32 email features
    features = extract_email_features(email_text, sender, subject)

    # [2] Cross-check links in email body with URL phishing model
    import re as _re
    urls_in_email = _re.findall(r'https?://[^\s<>"\'\)\]]+', email_text)
    url_scores = []
    links_flagged = 0
    for url in urls_in_email[:5]:  # limit to 5 URLs
        try:
            url_features = extract_features(url)
            url_result = detector.predict(url_features)
            url_scores.append(url_result["confidence"])
            if url_result["is_phishing"]:
                links_flagged += 1
        except Exception:
            pass

    # Inject URL model results into feature vector
    if url_scores:
        features["url_phishing_score"] = round(sum(url_scores) / len(url_scores), 4)
        features["any_link_phishing"] = int(links_flagged > 0)

    # [3] Pass sender domain for whitelist checking
    sender_domain = ""
    domain_match = _re.search(r'@([\w.-]+)', sender)
    if domain_match:
        sender_domain = domain_match.group(1).lower()
    features["_sender_domain"] = sender_domain

    # [4] Run XGBoost ML + heuristic ensemble detection
    prediction = email_detector.predict(features)

    result_label = prediction.get("result", "phishing" if prediction["is_phishing"] else "safe")
    confidence = round(prediction["confidence"], 4)
    risk_score = prediction.get("risk_score", int(round(confidence * 100)))

    # [5] Build enhanced response
    details = prediction.get("details", {})
    details["links_analyzed"] = len(url_scores)
    details["links_flagged"] = links_flagged
    if url_scores:
        details["avg_link_score"] = round(sum(url_scores) / len(url_scores), 4)

    response = {
        "result": result_label,
        "risk_score": risk_score,
        "risk_level": prediction.get("risk_level", "unknown"),
        "confidence": confidence,
        "reasons": prediction.get("reasons", []),
        "details": details,
        # Backward compatible fields
        "links_analyzed": len(url_scores),
        "avg_link_score": round(sum(url_scores) / max(len(url_scores), 1), 4) if url_scores else None,
    }

    # Log email request to SQLite (storing sender instead of URL for emails)
    database.log_request(f"email: {sender}", result_label, confidence, prediction.get("risk_level", "unknown"), ts)
    icons = {"phishing": "🔴 PHISHING", "suspicious": "⚠️  SUSPECT ", "safe": "✅ SAFE    "}
    icon = icons.get(result_label, "[?]")
    logger.info(f"  {icon}  risk={risk_score}%  conf={confidence*100:.0f}%  from={sender[:40]}")

    return jsonify(response), 200


# -- Legacy /analyze endpoint (backward compatible) ----------------------------
@app.route("/analyze", methods=["POST"])
def analyze():
    """Legacy endpoint - redirects to check_url logic with extended response."""
    data = request.get_json(silent=True)
    if not data or "url" not in data:
        return jsonify({"error": "Missing 'url' field"}), 400

    url = str(data["url"]).strip()
    tab_id = data.get("tab_id", "?")
    ts = datetime.datetime.utcnow().isoformat()

    if not url.startswith(("http://", "https://")):
        url = "https://" + url

    features = extract_features(url)
    result = detector.predict(features)

    result["url"] = url
    result["timestamp"] = ts
    result["features"] = features

    return jsonify(result), 200


# -- Report endpoint ----------------------------------------------------------
@app.route("/report", methods=["POST"])
@secure_endpoint
@limiter.limit("10 per minute")
def report_website():
    """Receive user feedback reporting a malicious site."""
    data = request.get_json(silent=True)
    if not data or "url" not in data:
        return jsonify({"error": "Missing 'url' field"}), 400

    report = {
        "url": str(data["url"]).strip(),
        "reason": data.get("reason", "User reported"),
        "timestamp": data.get("timestamp", datetime.datetime.utcnow().isoformat()),
        "ip": request.remote_addr,
    }

    database.log_report(report["url"], report["reason"], report["timestamp"], report["ip"])

    logger.info(f"[REPORT] {report['url'][:60]} — reason: {report['reason']}")

    return jsonify({"status": "received", "message": "Thank you for your report!"}), 200


# -- Analytics endpoint -------------------------------------------------------
@app.route("/analytics", methods=["GET"])
def analytics():
    """Returns aggregated stats from the request log database."""
    stats = database.get_analytics()
    return jsonify(stats)


# -- Health endpoint ----------------------------------------------------------
@app.route("/health", methods=["GET"])
@limiter.exempt
def health_check():
    return jsonify({
        "status": "ok",
        "service": "PhishGuard API v2.0",
        "url_model": detector.get_model_info(),
        "email_model": email_detector.get_model_info(),
        "database": "PostgreSQL (Supabase)" if database.USE_POSTGRES else "SQLite",
        "virustotal": "connected" if os.environ.get("VT_API_KEY", "").strip() else "not configured",
        "timestamp": datetime.datetime.utcnow().isoformat()
    })


# -- Test endpoint -------------------------------------------------------------
@app.route("/test", methods=["GET"])
def test():
    """Run a batch of sample URLs and return results."""
    samples = [
        ("https://www.google.com",                     False),
        ("https://github.com",                         False),
        ("https://paypal-secure-login.xyz/verify",     True),
        ("http://192.168.1.1/phishing-page",           True),
        ("https://amazon-account-update.club/login",   True),
        ("https://secure.paypa1.com/signin",           True),
        ("https://dropbox-file-share.tk/download",     True),
        ("https://netflix.com",                        False),
    ]

    results = []
    for url, expected in samples:
        feats = extract_features(url)
        result = detector.predict(feats)
        predicted = "phishing" if result["is_phishing"] else "safe"
        correct = result["is_phishing"] == expected
        results.append({
            "url":        url,
            "expected":   "phishing" if expected else "safe",
            "predicted":  predicted,
            "confidence": f"{result['confidence']*100:.0f}%",
            "risk_level": result["risk_level"],
            "correct":    correct
        })

    accuracy = sum(1 for r in results if r["correct"]) / len(results) * 100
    return jsonify({"accuracy": f"{accuracy:.0f}%", "results": results})


# -- Feedback receiver ---------------------------------------------------------
@app.route("/feedback", methods=["POST"])
def feedback():
    """Receive user-submitted feedback for ML retraining."""
    data = request.get_json(silent=True) or {}
    url = data.get('url', '')
    verdict = data.get('verdict', '')
    ts = datetime.datetime.utcnow().isoformat()
    
    logger.info(f"[Feedback] url={url} verdict={verdict}")
    if url and verdict:
        database.log_feedback(url, verdict, ts)
        
    return jsonify({"ok": True})


# -- Admin Dashboard & MLOps ---------------------------------------------------
@app.route("/admin", methods=["GET"])
def admin_dashboard():
    """Serve the Enterprise Admin Dashboard."""
    return render_template("admin.html")

@app.route("/admin/api/keys", methods=["GET", "POST"])
def admin_keys():
    """Manage enterprise API keys."""
    if request.method == "POST":
        data = request.get_json()
        key_id = data.get("key_id")
        company = data.get("company_name", "Unknown")
        ts = datetime.datetime.utcnow().isoformat()
        database.create_api_key(key_id, company, ts)
        return jsonify({"status": "created", "key": key_id})
    else:
        keys = database.get_all_api_keys()
        return jsonify(keys)

@app.route("/admin/api/retrain", methods=["POST"])
def trigger_retrain():
    """Trigger the MLOps retraining pipeline."""
    import threading
    import subprocess
    
    def run_pipeline():
        logger.info("[MLOps] Starting background retraining pipeline...")
        script_path = os.path.join(os.path.dirname(__file__), "ml", "retrain_pipeline.py")
        subprocess.run([sys.executable, script_path], check=False)
        logger.info("[MLOps] Retraining complete. Reloading model...")
        global email_detector
        # Hot-reload the model
        email_detector.__init__() 
        
    threading.Thread(target=run_pipeline, daemon=True).start()
    return jsonify({"status": "started", "message": "ML pipeline started in background. Model will hot-reload upon completion."})


# -- [01] Start server (multi-device access: host=0.0.0.0) --------------------
if __name__ == "__main__":
    print("\n" + "="*54)
    print("  PhishGuard API Server v2.0")
    print("  >  /check_url   - URL phishing detection")
    print("  >  /check_email - Email phishing detection")
    print("  >  /test        - run test batch")
    print("  >  /analytics   - stats dashboard")
    print("  >  /health      - service health")
    print("="*54 + "\n")
    app.run(debug=True, port=5000, host="0.0.0.0")
